defmodule Main do

  def main do

    # IO.puts("Punto 2")

    # productos = Listas.productos()

    # tiempo_secuencial = Benchmark.determinar_tiempo_ejecucion({Iva, :secuencial, [productos]})
    # IO.puts("Tiempo secuencial productos: #{tiempo_secuencial} ms")
    # tiempo_concurrente = Benchmark.determinar_tiempo_ejecucion({Iva, :concurrente, [productos]})
    # IO.puts("Tiempo concurrente productos: #{tiempo_concurrente} ms")
    # speedup = Benchmark.calcular_speedup(tiempo_secuencial, tiempo_concurrente)
    # IO.puts("Speedup productos: #{speedup}")

    IO.puts("----------------------------------------------------------")

    # IO.puts("\nPunto 4")
    # resenas = Listas.resenas()
    # secuencial_resenas = IO.inspect(Resena.secuencial(resenas))
    # concurrente_resenas = IO.inspect(Resena.concurrente(resenas))
    # tiempo_secuencial = Benchmark.determinar_tiempo_ejecucion({Resena, :secuencial, [resenas]})
    # IO.puts("Tiempo secuencial reseñas: #{tiempo_secuencial} ms")
    # tiempo_concurrente = Benchmark.determinar_tiempo_ejecucion({Resena, :concurrente, [resenas]})
    # IO.puts("Tiempo concurrente reseñas: #{tiempo_concurrente} ms")
    # speedup = Benchmark.calcular_speedup(tiempo_secuencial, tiempo_concurrente)
    # IO.puts("Speedup reseñas: #{speedup}")

    # IO.puts("----------------------------------------------------------")
    # IO.puts("\nPunto 6")
    # usuario= Listas.usuarios()
    # IO.puts("secuencial:")
    # secuencial_usuarios = IO.inspect(Usuario.secuencial(usuario))
    # IO.puts("concurrente:")
    # concurrente_usuarios = IO.inspect(Usuario.concurrente(usuario))
    # tiempo_secuencial = Benchmark.determinar_tiempo_ejecucion({Usuario, :secuencial, [usuario]})
    # IO.puts("Tiempo secuencial usuarios: #{tiempo_secuencial} ms")
    # tiempo_concurrente = Benchmark.determinar_tiempo_ejecucion({Usuario, :concurrente, [usuario]})
    # IO.puts("Tiempo concurrente usuarios: #{tiempo_concurrente} ms")
    # speedup = Benchmark.calcular_speedup(tiempo_secuencial, tiempo_concurrente)
    # IO.puts("Speedup usuarios: #{speedup}")

    IO.puts("----------------------------------------------------------")
    # IO.puts("\nPunto 8")
    # tareas = Listas.tareas()
    # IO.puts("secuencial:")
    # secuencial_tareas = IO.inspect(Mantenimiento.secuencial(tareas))
    # IO.puts("concurrente:")
    # concurrente_tareas = IO.inspect(Mantenimiento.concurrente(tareas))
    # tiempo_secuencial = Benchmark.determinar_tiempo_ejecucion({Mantenimiento, :secuencial, [tareas]})
    # IO.puts("Tiempo secuencial tareas: #{tiempo_secuencial} ms")
    # tiempo_concurrente = Benchmark.determinar_tiempo_ejecucion({Mantenimiento, :concurrente, [tareas]})
    # IO.puts("Tiempo concurrente tareas: #{tiempo_concurrente} ms")
    # speedup = Benchmark.calcular_speedup(tiempo_secuencial, tiempo_concurrente)
    # IO.puts("Speedup tareas: #{speedup}")

    # IO.puts("----------------------------------------------------------")
    # IO.puts("\nPunto 10")
    # paquetes = Listas.paquetes()
    # IO.puts("secuencial:")
    # secuencial_paquetes = IO.inspect(Paquete.secuencial(paquetes))
    # IO.puts("concurrente:")
    # concurrente_paquetes = IO.inspect(Paquete.concurrente(paquetes))
    # tiempo_secuencial = Benchmark.determinar_tiempo_ejecucion({Paquete, :secuencial, [paquetes]})
    # IO.puts("Tiempo secuencial paquetes: #{tiempo_secuencial} ms")
    # tiempo_concurrente = Benchmark.determinar_tiempo_ejecucion({Paquete, :concurrente, [paquetes]})
    # IO.puts("Tiempo concurrente paquetes: #{tiempo_concurrente} ms")
    # speedup = Benchmark.calcular_speedup(tiempo_secuencial, tiempo_concurrente)
    # IO.puts("Speedup paquetes: #{speedup}")

    IO.puts("----------------------------------------------------------")
    IO.puts("\nPunto 12")
    plantillas = Listas.plantillas()
    IO.puts("secuencial:")
    secuencial_plantillas = IO.inspect(Tpl.procesar_secuencial(plantillas))
    IO.puts("concurrente:")
    concurrente_plantillas = IO.inspect(Tpl.procesar_concurrente(plantillas))
    tiempo_secuencial = Benchmark.determinar_tiempo_ejecucion({Tpl, :procesar_secuencial, [plantillas]})
    IO.puts("Tiempo secuencial plantillas: #{tiempo_secuencial} ms")
    tiempo_concurrente = Benchmark.determinar_tiempo_ejecucion({Tpl, :procesar_concurrente, [plantillas]})
    IO.puts("Tiempo concurrente plantillas: #{tiempo_concurrente} ms")
    speedup = Benchmark.calcular_speedup(tiempo_secuencial, tiempo_concurrente)
    IO.puts("Speedup plantillas: #{speedup}")

  end
end
Main.main()
